artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1gA0dJ7JwT-_25jTOKLah3tHLq5yZBSJ8/view?usp=share_link
  local_data_file: artifacts/data_ingestion/ncaa_data.zip
  unzip_dir: artifacts/data_ingestion/ncaa_data

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/model.joblib
  train_data_path: artifacts/data_ingestion/processed/tourney_games_features.csv
  feature_columns_file: artifacts/data_ingestion/processed/feature_columns.csv
  test_size: 0.2

model_analysis:
  root_dir: artifacts/model_analysis
  model_path: artifacts/model_trainer/model.joblib
  calibrator_path: artifacts/model_trainer/calibrator.joblib
  submission_path: artifacts/model_trainer/submission.csv
  train_data_path: artifacts/data_ingestion/processed/tourney_games_features.csv
  feature_columns_file: artifacts/data_ingestion/processed/feature_columns.csv
  analysis_reports_dir: artifacts/model_analysis/reports

dashboard:
  root_dir: artifacts/dashboard
  model_path: artifacts/model_trainer/model.joblib
  analysis_dir: artifacts/model_analysis
  template_dir: artifacts/dashboard/templates
  static_dir: artifacts/dashboard/static
  submission_path: artifacts/model_trainer/submission.csv
  host: "0.0.0.0"
  port: 8050